application: amazonbooklookup
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: .*
  script: testyaml.app #not sure wahy it needs the "app" extension

libraries:
- name: webapp2
  version: "2.5.1"
